trigger:
  branches:
    include:
      - main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        version: $(dotNetVersion)
        includePreviewVersions: false

    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'
      
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '$(solution)'
        feedsToUse: 'config'
        nugetConfigPath: 'nuget.config'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Web API'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'webapi'
        publishLocation: 'Container'

- stage: DeployToTest
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployTest
    environment: 'test'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'webapi'
          
          - task: AzureKeyVault@2
            displayName: 'Azure Key Vault - Test'
            inputs:
              azureSubscription: 'SMD-KeyVault'
              KeyVaultName: 'test-key-vault-v2'
              RunAsPreJob: false

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              appName: 'smd-webapi-test'
              package: '$(Pipeline.Workspace)/webapi/*.zip'
              deploymentMethod: 'auto'
              appSettings: >
                -Logging__LogLevel__Default "Information"
                -Logging__LogLevel__Microsoft.AspNetCore "Warning"
                -TwitterAPI__timelineEmbedUrl "$(TimelineEmbedUrl)"
                -NotificationSettings__SendGridApiKey "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/SMD--SendGridApiKey)"
                -NotificationSettings__SendGridFromEmail "$(TestSendGridFromEmail)"
                -NotificationSettings__SendGridFromName "$(TestSendGridFromName)"
                -AppSettings__DopamineDetoxUrl "$(TestDopamineDetoxUrl)"
                -AppSettings__OPENAI_API_KEY "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/OpenAI--Api-Key)"
                -Jwt__Key "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/SMD--JwtKey)"
                -Jwt__Issuer "$(TestJwtIssuer)"
                -Jwt__Audience "$(TestJwtAudience)"
                -Authentication__Google__ClientId "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/Google--ClientId)"
                -Authentication__Google__ClientSecret "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/Google--ClientSecret)"
                -ConnectionStrings__DefaultConnection "@Microsoft.KeyVault(SecretUri=https://test-key-vault-v2.vault.azure.net/secrets/ProjectDb--SQL-DefaultConnectionString)"

- stage: DeployToProd
  dependsOn: DeployToTest
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    environment: 'production'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: 'webapi'
          
          - task: AzureKeyVault@2
            displayName: 'Azure Key Vault - Production'
            inputs:
              azureSubscription: 'SMD-KeyVault'
              KeyVaultName: 'prod-key-vault-v1'
              RunAsPreJob: false

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              appName: 'smd-webapi-prod'
              package: '$(Pipeline.Workspace)/webapi/*.zip'
              deploymentMethod: 'auto'
              appSettings: >
                -Logging__LogLevel__Default "Information"
                -Logging__LogLevel__Microsoft.AspNetCore "Warning"
                -TwitterAPI__timelineEmbedUrl "$(TimelineEmbedUrl)"
                -NotificationSettings__SendGridApiKey "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/SMD--SendGridApiKey)"
                -NotificationSettings__SendGridFromEmail "$(ProdSendGridFromEmail)"
                -NotificationSettings__SendGridFromName "$(ProdSendGridFromName)"
                -AppSettings__DopamineDetoxUrl "$(ProdDopamineDetoxUrl)"
                -AppSettings__OPENAI_API_KEY "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/OpenAI--Api-Key)"
                -Jwt__Key "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/SMD--JwtKey)"
                -Jwt__Issuer "$(ProdJwtIssuer)"
                -Jwt__Audience "$(ProdJwtAudience)"
                -Authentication__Google__ClientId "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/Google--ClientId)"
                -Authentication__Google__ClientSecret "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/Google--ClientSecret)"
                -ConnectionStrings__DefaultConnection "@Microsoft.KeyVault(SecretUri=https://prod-key-vault-v1.vault.azure.net/secrets/ProjectDb--SQL-DefaultConnectionString)"